
[location_message]
	ss = false
	early_enter_alert = false
	paste_early_enters_into_party_chat = false
	toggle_selected_location_message = false
	pre_4 = false
	pre_3 = false
	fast_leap = false
	pre_2 = false
	mid = false
	location_notification_sound = "note.harp"
	location_notifications = false
	core = false
	location_notification_sound_times_to_play = "1"
	safespot_2 = false
	tunnel = false

[general]
	auto_potion_bag = false
	hide_players = true
	compact_hoppity = true

	[general.auto_refill]
		sp_booms = true
		sp_booms_threshold = 32
		jerries = false
		pearls = true
		jerries_threshold = 32
		pearls_threshold = 8

	[general.mask_gui]
		ready_indicator_color = 10
		cooldown_timer_color = 12
		mask_gui = false
		mask_name_color = 6

	[general.blood]
		bc_helper = false

[chat]
	chat_cleaner = true
	auto_chat_p = true

[secrets]
	show_clicked_secrets = true
	clicked_secrets_sound = true
	pitch_of_secret_click_sound = 1.0
	select_secret_clicked_sound = 3
	volume_of_secret_click_sound = 1.0
	clicked_secrets_color = "255,0,255,0"

[notifications]
	wish = false
	section_done = false
	bat = false
	cloak = false
	key_sound = false
	blood = false
	key = true
	pet = false

["f7/m7"]
	i4helper = false
	goldor_tick_timer = false
	predev_timer = false
	lever_aura = false
	melody_warning = false
	p3_start_timer = false
	terminal_gui = false
	golder_tick_timer = false
	crystal_info = false
	wither_stuck_title = false

	["f7/m7".p3]
		i4helper = false
		goldor_tick_timer = false
		esp_color = "255,0,255,0"
		esp = false
		lever_aura = false
		melody_warning = false
		p3_start_timer = false
		terminal_gui = false
		timestamps = false

	["f7/m7".terminals]
		esp_color = "255,0,255,0"
		esp = false
		terminal_gui = false
		timestamps = false

