
[location_message]
	ss = true
	early_enter_alert = true
	paste_early_enters_into_party_chat = true
	toggle_selected_location_message = true
	pre_4 = false
	pre_3 = true
	fast_leap = true
	pre_2 = true
	mid = true
	location_notification_sound = "note.harp"
	location_notifications = false
	core = true
	location_notification_sound_times_to_play = "1"
	safespot_2 = true
	tunnel = true

[general]
	auto_potion_bag = false
	hide_players = true
	compact_hoppity = true

	[general.auto_refill]
		sp_booms = true
		sp_booms_threshold = 24
		jerries = false
		pearls = true
		jerries_threshold = 32
		pearls_threshold = 8

	[general.mask_gui]
		ready_indicator_color = 10
		cooldown_timer_color = 12
		mask_gui = true
		mask_name_color = 9

	[general.blood]
		bc_helper = true

[chat]
	chat_cleaner = true
	auto_chat_p = true

[secrets]
	show_clicked_secrets = true
	clicked_secrets_sound = true
	pitch_of_secret_click_sound = 0.86153847
	select_secret_clicked_sound = 1
	volume_of_secret_click_sound = 1.0
	clicked_secrets_color = "255,0,255,194"

[notifications]
	wish = true
	section_done = true
	bat = true
	cloak = true
	key_sound = true
	blood = true
	key = true
	pet = true

["f7/m7"]
	i4helper = false
	goldor_tick_timer = false
	predev_timer = true
	lever_aura = false
	melody_warning = false
	p3_start_timer = false
	terminal_gui = false
	golder_tick_timer = false
	crystal_info = true
	wither_stuck_title = true

	["f7/m7".p3]
		i4helper = true
		goldor_tick_timer = true
		esp_color = "255,0,211,234"
		esp = true
		lever_aura = true
		melody_warning = true
		p3_start_timer = true
		terminal_gui = true
		timestamps = true

	["f7/m7".terminals]
		esp_color = "255,0,255,0"
		esp = false
		terminal_gui = false
		timestamps = false

