import { Command } from "./commands/Command"



import "./util/FirstInstall"
import "./features/MaskGui"
import "./features/i4helper"
import "./features/eetitles"
import "./features/AtLocationMessages"
import "./features/CrystalInfo"
import "./features/PredevTimer"
import "./features/Terminal"
import "./features/WitherStuck"
import "./features/Keypickup"
import "./features/ChatCleaner"
import "./features/BloodDone"
import "./features/BatTitle"
import "./features/AutoPchat"
import "./features/Wish"
import "./features/WitherCloak"
import "./features/AutoPets"
import "./features/p3sectiondone"
import "./features/BCHelper"
import "./features/secretsclicked"
import "./commands/epcommand"
import "./commands/spcommand"